apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: apicurio-registry
spec:
  app:
    storage:
      type: kafkasql
      kafkasql:
        bootstrapServers: test-cluster-kafka-bootstrap.kafka.svc:9092
