apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: streamshub-console
spec:
  hostname: console.streamshub.local
  kafkaClusters:
    - name: test-cluster
      namespace: kafka
      listener: plain
